# Generated by Django 5.0.3 on 2024-03-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback_entries',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
